/* Automatically generated by ../../tools/pmGenPmFeatures.py on Thu Nov 14 18:31:58 2013.  DO NOT EDIT. */
#define HAVE_PRINT
#define HAVE_REPLICATION
#define HAVE_DEFAULTARGS
#define HAVE_DEL
#define HAVE_BACKTICK
#define HAVE_GC
#define HAVE_STRING_FORMAT
#define HAVE_IMPORTS
